name: Deployment

on: 
  release:
    types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                distribution: 'zulu'
                java-version: 11

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle
              env:
                packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
              run: |
                ./gradlew build

            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@2201.7.0
              with:
                args:
                  pack mongodb
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'rootfs'
                scan-ref: '.'
                skip-dirs: 'gradle/'
                format: 'table'
                timeout: '10m0s'
                exit-code: '1'
                
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@2201.7.0
              with:
                  args:
                      push
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
                  WORKING_DIR: ./mongodb
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
